In [76]:
from utils import *
import pandas as pd

# Data Types in Python

In Python, data can be stored in different forms. These forms are called **data types**.

Different data types are needed because different kinds of data behave differently.  
For example:

- a **name** is text
- an **age** is a number
- a **price** can be a decimal value
- a **count** of someting is integar
- multiple values can be stored in a collection

Using different data types helps Python understand:
- what kind of data is being stored
- what operations can be performed on that data

## Some Important Python Data Types

- **int** → whole numbers like `10`, `25`
- **float** → decimal numbers like `10.5`, `99.99`
- **str** → text like `"Bhupesh"`
- **bool** → `True` or `False`
- **list** → ordered collection of items: `['hello', 1, 'Bhupesh', 31]`
- **dict** → data stored in key-value pairs: `{
    "name": "Bhupesh",
    "roll": 1234,
    "city": "Dallas"
}`

## Focus for This Section

In this notebook, we will cover two important Python data types:

- **List**
- **Dictionary**

These are very commonly used in Python and are especially useful in data analysis and pandas.

# List in Python

A list stores multiple items in one variable.

Lists are written using square brackets `[]`.

In [59]:
fruits = ["apple", "banana", "mango"]

print(fruits)

['apple', 'banana', 'mango']

## List can store different data types

A list can contain strings, numbers, and other values.

In [60]:
data = ["Bhupesh", 1234, "Dallas", 95.5]

print(data)

['Bhupesh', 1234, 'Dallas', 95.5]

## Access items from a list

Each item in a list has an index.

Index starts from `0`.

In [61]:
print(fruits[0])
print(fruits[1])
print(fruits[2])

apple
banana
mango

## Add an item to a list

Use `append()` to add a new item at the end.

In [62]:
fruits.append("orange")

print(fruits)

['apple', 'banana', 'mango', 'orange']

## Change an item in a list

We can update a value using its index.

In [63]:
fruits[1] = "grapes"

print(fruits)

['apple', 'grapes', 'mango', 'orange']

## Remove an item from a list

Use `remove()` to delete an item.

In [64]:
fruits.remove("apple")

print(fruits)

['grapes', 'mango', 'orange']

## Length of a list

Use `len()` to find how many items are in the list.

In [65]:
print(len(fruits))

3

## Create a DataFrame from a list

A list can be converted into a pandas DataFrame.

In [66]:
import pandas as pd

names = ["Bhupesh", "Rahul", "Aman"]

df = pd.DataFrame(names, columns=["Name"])
print(df)

      Name
0  Bhupesh
1    Rahul
2     Aman

## List of lists

A list can also contain other lists.

This is useful for table-like data.

In [67]:
student_data = [
    ["Bhupesh", 101, "Dallas"],
    ["Rahul", 102, "Boston"],
    ["Aman", 103, "Austin"]
]

print(student_data)

[['Bhupesh', 101, 'Dallas'], ['Rahul', 102, 'Boston'], ['Aman', 103, 'Austin']]

## Create a DataFrame from a list of lists

Each inner list becomes one row in the DataFrame.

In [73]:
df2 = pd.DataFrame(student_data, columns=["Name", "Roll", "City"])
df2

      Name  Roll    City
0  Bhupesh   101  Dallas
1    Rahul   102  Boston
2     Aman   103  Austin

# Practice Task 1: Create a List

Create a list named `students` with the following names in the same order:

`Bhupesh`, `Rahul`, `Aman`, `Neha`, `Riya`

In [81]:
students =

In [80]:
verify_task_1(students)

Correct

# Practice Task 2: Remove and Insert

Use the same list `students`.

1. Remove the name at index `2`
2. Insert `"Karan"` at index `2`

Print the updated list.

In [ ]:
# Code

In [ ]:
verify_task_2(students)

# Practice Task 3: Append and Change

Use the updated list `students`.

1. Add `"Simran"` at the end of the list
2. Change the value at index `1` to `"Arjun"`

Print the final list.

In [ ]:
verify_task_3(students)

# Dictionary in Python

A dictionary stores data in **key-value pairs**. They are written using `{}

- **Key** = label
- **Value** = data

Example:
- `"name"` is a key
- `"Bhupesh"` is a value

In [72]:
student = {
    "name": "Bhupesh",
    "roll": 1234,
    "city": "Dallas"
}

print(student)

{'name': 'Bhupesh', 'roll': 1234, 'city': 'Dallas'}

## Access values from a dictionary

We use the key to get its value.

In [39]:
print(student["name"])
print(student["roll"])
print(student["city"])

Bhupesh
1234
Dallas

## Dictionary with lists

In a dictionary, one value can also be a list.

This is useful when we want to store multiple rows of data under each key.

In [84]:
student_data = {
    "name": ["Bhupesh", "Rahul", "Aman"],  # key and list of values for each key
    
    "roll": [101, 102, 103],
    
    "city": ["Dallas", "Boston", "Austin"]
}

print(student_data)

{'name': ['Bhupesh', 'Rahul', 'Aman'], 'roll': [101, 102, 103], 'city': ['Dallas', 'Boston', 'Austin']}

In [85]:
student_data['name']

['Bhupesh', 'Rahul', 'Aman']

In [86]:
#acessing first value of the name
student_data['name'][0]

'Bhupesh'

## Create a DataFrame from a dictionary with lists

When dictionary values are lists:
- keys become column names
- list items become rows

In [46]:
df = pd.DataFrame(student_data)
df

      name  roll    city
0  Bhupesh   101  Dallas
1    Rahul   102  Boston
2     Aman   103  Austin

# Practice Task 1: Create a Dictionary

Create a dictionary named `student` with the following key-value pairs:

- `"name"` → `"Bhupesh"`
- `"roll"` → `1234`
- `"city"` → `"Dallas"`

In [ ]:
#your code

In [ ]:
verify_task_4(student)

# Practice Task 2: Update a Dictionary

Use the same dictionary `student`.

Perform these steps:

1. Change `"city"` to `"Boston"`
2. Add a new key `"course"` with value `"Python"`

Print the updated dictionary.

In [ ]:
#your code

In [ ]:
verify_task_5(student)

# Practice Task 3: Remove and Add Keys

Create a dictionary named `employee` with:

- `"name"` → `"Rahul"`
- `"id"` → `101`
- `"department"` → `"Sales"`
- `"location"` → `"Chicago"`

Then perform these steps:

1. Remove the key `"location"`
2. Add a new key `"salary"` with value `50000`

Print the final dictionary.

In [ ]:
#your code

In [ ]:
verify_task_6(employee)